#! /usr/bin/env ruby

$: << File.dirname(__FILE__)

require "rubygems"
require "bundler/setup"
require "eventmachine"

require "mailroom"

timers = {}

trap("QUIT") do
  Mailroom::MailSpoolSnapshotter.halt!
end

trap("INT") do
  EventMachine::stop_event_loop
end

begin
  EventMachine::run do
    ARGV.each do |mailspool|
      Mailroom::MailSpoolSnapshotter.new(mailspool)
    end
  end

  Mailroom.logger.info "Exiting."
rescue Exception => e
  Mailroom.logger.fatal "#{e}\n#{e.backtrace.join("\n")}"
  HoptoadNotifier.notify(e)
  raise
end
