#! /usr/bin/env ruby
require File.expand_path("./init.rb", File.dirname(__FILE__))
require "daemons"

Daemons.run(File.join(File.dirname(__FILE__), 'mailroomd.rb'),
            :dir_mode => :normal,
            :dir => Mailroom.pid_directory)
